# Generated by Django 2.2.1 on 2019-05-31 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190531_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='h',
            new_name='heading',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='c',
        ),
    ]
