# Generated by Django 2.2.1 on 2019-05-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190531_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.CharField(default='content', max_length=999999999999),
        ),
    ]
